version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.14.1

        working_directory: ~/repo
        environment:
            MONGO_URI: $MONGO_URI
        steps:
            - checkout
            - run: ls -l ~/repo
            - run: yarn install
            - run: NODE_ENV=testing yarn start
            - run: ci:test
