version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.14.1

        working_directory: ~/repo
        steps:
            - checkout
            - run: ls -l ~/repo
            - run: yarn install
            - run:
                  name: 'What is my mongo uri?'
                  command: echo ${MONGO_URI}
            - run: NODE_ENV=testing yarn start
            - run: ci:test
