version: 2
orbs:
    # use Cypress orb from CircleCI registry
    cypress: cypress-io/cypress@1.5.1
jobs:
    build:
        docker:
            - image: circleci/node:10.14.1
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                  name: 'Install Packages'
                  command: 'yarn install'
            - run:
                  name: 'Mongo URI:'
                  command: echo ${MONGO_URI}
            - run:
                  name: 'Run Testing Environment'
                  command: 'NODE_ENV=testing MONGO_URI=${MONGO_URI} yarn start & yarn run cypress run'
